// src/redux/constants/authConstants.js

// User Login
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';
export const USER_LOGIN_RESET = 'USER_LOGIN_RESET';

// Client Signup
export const CLIENT_SIGNUP_REQUEST = 'CLIENT_SIGNUP_REQUEST';
export const CLIENT_SIGNUP_SUCCESS = 'CLIENT_SIGNUP_SUCCESS';
export const CLIENT_SIGNUP_FAIL = 'CLIENT_SIGNUP_FAIL';
export const CLIENT_SIGNUP_RESET = 'CLIENT_SIGNUP_RESET';

// Freelancer Signup
export const FREELANCER_SIGNUP_REQUEST = 'FREELANCER_SIGNUP_REQUEST';
export const FREELANCER_SIGNUP_SUCCESS = 'FREELANCER_SIGNUP_SUCCESS';
export const FREELANCER_SIGNUP_FAIL = 'FREELANCER_SIGNUP_FAIL';
export const FREELANCER_SIGNUP_RESET = 'FREELANCER_SIGNUP_RESET';

// Add this constant
export const USER_LOGOUT = 'USER_LOGOUT';




